spring:
  application:
    name: agentic-ai-crypto
  datasource:
    url: jdbc:postgresql://localhost:5432/agent_memory
    username: postgres
    password: postgres
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        initialize-schema: true

#logging:
#  level:
#    root: error

server:
  port: 9292
